// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package android

import (
	"testing"
)

// Data from this test was generated by the Android reference application.
func TestGetNonce(t *testing.T) {
	testData := []struct {
		Keys    []string
		Regions []string
		Nonce   string
	}{
		{[]string{"x21Goi8X9m/glOZ0+wz8fA", "2mvFSmRsFmJR5r07dxGSjg", "6bAd3dv7p+VEuaJVkVItaQ"},
			[]string{"GB", "US"},
			"UWvJuvgf7SGAAprY8iH1rQzm/lstr1SGRWQu4i7FMEs",
		},
		{[]string{"zdCW5HrOKbirxmQVc0L/eA", "t+k51ifogJo9jq3GH9LWGQ", "3uXRrSlcv1+OMI3oFtdaUw"},
			[]string{"gB", "us"},
			"R6k7EOVS8kpV4zmPm9DbAbEspN1FA6qHC1T9q8bPvyo",
		},
	}

	for _, input := range testData {
		data := NewNonce(appPackage, input.Keys, input.Regions)
		nonce := data.Nonce()
		if nonce != input.Nonce {
			t.Errorf("getNonce: got '%v', want '%v'", nonce, input.Nonce)
		}
	}
}
