// Code generated by gen-metrics-registrar. DO NOT EDIT.
package metricsregistrar

import (
	_ "github.com/google/exposure-notifications-server/internal/backup"
	_ "github.com/google/exposure-notifications-server/internal/cleanup"
	_ "github.com/google/exposure-notifications-server/internal/export"
	_ "github.com/google/exposure-notifications-server/internal/exportimport"
	_ "github.com/google/exposure-notifications-server/internal/federationin"
	_ "github.com/google/exposure-notifications-server/internal/federationout"
	_ "github.com/google/exposure-notifications-server/internal/generate"
	_ "github.com/google/exposure-notifications-server/internal/jwks"
	_ "github.com/google/exposure-notifications-server/internal/keyrotation"
	_ "github.com/google/exposure-notifications-server/internal/mirror"
	_ "github.com/google/exposure-notifications-server/internal/publish"
	_ "github.com/google/exposure-notifications-server/internal/storage"
)
