// Copyright 2020 the Exposure Notifications Server authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: internal/pb/revision.proto

package pb

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RevisionToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kid  string `protobuf:"bytes,1,opt,name=kid,proto3" json:"kid,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RevisionToken) Reset() {
	*x = RevisionToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_revision_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevisionToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevisionToken) ProtoMessage() {}

func (x *RevisionToken) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_revision_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevisionToken.ProtoReflect.Descriptor instead.
func (*RevisionToken) Descriptor() ([]byte, []int) {
	return file_internal_pb_revision_proto_rawDescGZIP(), []int{0}
}

func (x *RevisionToken) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

func (x *RevisionToken) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RevisionTokenData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RevisableKeys []*RevisableKey `protobuf:"bytes,1,rep,name=revisableKeys,proto3" json:"revisableKeys,omitempty"`
}

func (x *RevisionTokenData) Reset() {
	*x = RevisionTokenData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_revision_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevisionTokenData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevisionTokenData) ProtoMessage() {}

func (x *RevisionTokenData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_revision_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevisionTokenData.ProtoReflect.Descriptor instead.
func (*RevisionTokenData) Descriptor() ([]byte, []int) {
	return file_internal_pb_revision_proto_rawDescGZIP(), []int{1}
}

func (x *RevisionTokenData) GetRevisableKeys() []*RevisableKey {
	if x != nil {
		return x.RevisableKeys
	}
	return nil
}

type RevisableKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemporaryExposureKey []byte `protobuf:"bytes,1,opt,name=temporaryExposureKey,proto3" json:"temporaryExposureKey,omitempty"`
	IntervalNumber       int32  `protobuf:"varint,2,opt,name=intervalNumber,proto3" json:"intervalNumber,omitempty"`
	IntervalCount        int32  `protobuf:"varint,3,opt,name=intervalCount,proto3" json:"intervalCount,omitempty"`
}

func (x *RevisableKey) Reset() {
	*x = RevisableKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_revision_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevisableKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevisableKey) ProtoMessage() {}

func (x *RevisableKey) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_revision_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevisableKey.ProtoReflect.Descriptor instead.
func (*RevisableKey) Descriptor() ([]byte, []int) {
	return file_internal_pb_revision_proto_rawDescGZIP(), []int{2}
}

func (x *RevisableKey) GetTemporaryExposureKey() []byte {
	if x != nil {
		return x.TemporaryExposureKey
	}
	return nil
}

func (x *RevisableKey) GetIntervalNumber() int32 {
	if x != nil {
		return x.IntervalNumber
	}
	return 0
}

func (x *RevisableKey) GetIntervalCount() int32 {
	if x != nil {
		return x.IntervalCount
	}
	return 0
}

var File_internal_pb_revision_proto protoreflect.FileDescriptor

var file_internal_pb_revision_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x72, 0x65,
	0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x35, 0x0a, 0x0d,
	0x52, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x48, 0x0a, 0x11, 0x52, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x33, 0x0a, 0x0d, 0x72, 0x65, 0x76, 0x69,
	0x73, 0x61, 0x62, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x52, 0x65, 0x76, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x0d,
	0x72, 0x65, 0x76, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x73, 0x22, 0x90, 0x01,
	0x0a, 0x0c, 0x52, 0x65, 0x76, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x32,
	0x0a, 0x14, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x72, 0x79, 0x45, 0x78, 0x70, 0x6f, 0x73,
	0x75, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x14, 0x74, 0x65,
	0x6d, 0x70, 0x6f, 0x72, 0x61, 0x72, 0x79, 0x45, 0x78, 0x70, 0x6f, 0x73, 0x75, 0x72, 0x65, 0x4b,
	0x65, 0x79, 0x12, 0x26, 0x0a, 0x0e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x76, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x0d, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x42, 0x40, 0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x65, 0x78, 0x70, 0x6f, 0x73, 0x75, 0x72, 0x65, 0x2d, 0x6e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2d, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x3b,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_pb_revision_proto_rawDescOnce sync.Once
	file_internal_pb_revision_proto_rawDescData = file_internal_pb_revision_proto_rawDesc
)

func file_internal_pb_revision_proto_rawDescGZIP() []byte {
	file_internal_pb_revision_proto_rawDescOnce.Do(func() {
		file_internal_pb_revision_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_pb_revision_proto_rawDescData)
	})
	return file_internal_pb_revision_proto_rawDescData
}

var file_internal_pb_revision_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_pb_revision_proto_goTypes = []interface{}{
	(*RevisionToken)(nil),     // 0: RevisionToken
	(*RevisionTokenData)(nil), // 1: RevisionTokenData
	(*RevisableKey)(nil),      // 2: RevisableKey
}
var file_internal_pb_revision_proto_depIdxs = []int32{
	2, // 0: RevisionTokenData.revisableKeys:type_name -> RevisableKey
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_pb_revision_proto_init() }
func file_internal_pb_revision_proto_init() {
	if File_internal_pb_revision_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_pb_revision_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RevisionToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_revision_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RevisionTokenData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_revision_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RevisableKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_pb_revision_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_pb_revision_proto_goTypes,
		DependencyIndexes: file_internal_pb_revision_proto_depIdxs,
		MessageInfos:      file_internal_pb_revision_proto_msgTypes,
	}.Build()
	File_internal_pb_revision_proto = out.File
	file_internal_pb_revision_proto_rawDesc = nil
	file_internal_pb_revision_proto_goTypes = nil
	file_internal_pb_revision_proto_depIdxs = nil
}
