options:
  env:
  - 'KO_DOCKER_REPO=us.gcr.io/${PROJECT_ID}'
  - 'DOCKER_REPO_OVERRIDE=us.gcr.io/${PROJECT_ID}'
steps:
# Build ko, prerequisite.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/ko', '-f', 'terraform/ko.Dockerfile', 'terraform/']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/ko']
# Tests
- name: 'mirror.gcr.io/library/golang'
  env:
  - GO111MODULE=on
  args: ['go', 'test', './...']
# Build and publish containers`
- name: 'gcr.io/$PROJECT_ID/ko'
  args:
  - publish
  - -P
  - ./cmd/export
- name: 'gcr.io/$PROJECT_ID/ko'
  args:
  - publish
  - -P
  - ./cmd/federationin
- name: 'gcr.io/$PROJECT_ID/ko'
  args:
  - publish
  - -P
  - ./cmd/federationout
- name: 'gcr.io/$PROJECT_ID/ko'
  args:
  - publish
  - -P
  - ./cmd/exposure
- name: 'gcr.io/$PROJECT_ID/ko'
  args:
  - publish
  - -P
  - ./cmd/cleanup-export
- name: 'gcr.io/$PROJECT_ID/ko'
  args:
  - publish
  - -P
  - ./cmd/cleanup-exposure
