#!/usr/bin/env bash

# Copyright 2020 the Exposure Notifications Server authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eEuo pipefail

DB_PORT=${DB_PORT:-5432}

if [ -z "${DB_CONN:-}" ]; then
  echo "missing DB_CONN"
  exit 1
fi

function cleanup {
  echo "==> Terminating proxy (PID ${CLOUD_SQL_PID})"
  if [ -n "${CLOUD_SQL_PID:-}" ]; then
    kill -SIGINT "${CLOUD_SQL_PID}"
  fi
}

echo "==> Staring Cloud SQL Proxy"
/cloud-sql-proxy -instances=${DB_CONN}=tcp:${DB_PORT} -term_timeout=60s -verbose &
CLOUD_SQL_PID=$!
trap cleanup EXIT

echo "==> Waiting for proxy to be ready"
sleep 5

echo "==> Running command ($@)"
$@
