# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# Deploys a Cloud Run service.
#

substitutions:
  _REGION:
  _REPO: 'github.com/google/exposure-notifications-server'
  _TAG:

steps:
#
# cleanup-exposure
#
- id: 'deploy-cleanup-exposure'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:307.0.0-alpine'
  args:
  - 'bash'
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |-
    gcloud run deploy "cleanup-exposure" \
      --quiet \
      --project "${PROJECT_ID}" \
      --platform "managed" \
      --region "${_REGION}" \
      --image "gcr.io/${PROJECT_ID}/${_REPO}/cleanup-exposure:${_TAG}" \
      --no-traffic
  waitFor:
  - '-'

#
# cleanup-export
#
- id: 'deploy-cleanup-export'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:307.0.0-alpine'
  args:
  - 'bash'
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |-
    gcloud run deploy "cleanup-export" \
      --quiet \
      --project "${PROJECT_ID}" \
      --platform "managed" \
      --region "${_REGION}" \
      --image "gcr.io/${PROJECT_ID}/${_REPO}/cleanup-export:${_TAG}" \
      --no-traffic
  waitFor:
  - '-'

#
# debugger
#
- id: 'deploy-debugger'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:307.0.0-alpine'
  args:
  - 'bash'
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |-
    gcloud run deploy "debugger" \
      --quiet \
      --project "${PROJECT_ID}" \
      --platform "managed" \
      --region "${_REGION}" \
      --image "gcr.io/${PROJECT_ID}/${_REPO}/debugger:${_TAG}" \
      --no-traffic
  waitFor:
  - '-'

#
# export
#
- id: 'deploy-export'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:307.0.0-alpine'
  args:
  - 'bash'
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |-
    gcloud run deploy "export" \
      --quiet \
      --project "${PROJECT_ID}" \
      --platform "managed" \
      --region "${_REGION}" \
      --image "gcr.io/${PROJECT_ID}/${_REPO}/export:${_TAG}" \
      --no-traffic
  waitFor:
  - '-'

#
# exposure
#
- id: 'deploy-exposure'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:307.0.0-alpine'
  args:
  - 'bash'
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |-
    gcloud run deploy "exposure" \
      --quiet \
      --project "${PROJECT_ID}" \
      --platform "managed" \
      --region "${_REGION}" \
      --image "gcr.io/${PROJECT_ID}/${_REPO}/exposure:${_TAG}" \
      --no-traffic
  waitFor:
  - '-'

#
# federationin
#
- id: 'deploy-federationin'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:307.0.0-alpine'
  args:
  - 'bash'
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |-
    gcloud run deploy "federationin" \
      --quiet \
      --project "${PROJECT_ID}" \
      --platform "managed" \
      --region "${_REGION}" \
      --image "gcr.io/${PROJECT_ID}/${_REPO}/federationin:${_TAG}" \
      --no-traffic
  waitFor:
  - '-'

#
# federationout
#
- id: 'deploy-federationout'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:307.0.0-alpine'
  args:
  - 'bash'
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |-
    gcloud run deploy "federationout" \
      --quiet \
      --project "${PROJECT_ID}" \
      --platform "managed" \
      --region "${_REGION}" \
      --image "gcr.io/${PROJECT_ID}/${_REPO}/federationout:${_TAG}" \
      --no-traffic
  waitFor:
  - '-'

#
# generate
#
- id: 'deploy-generate'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:307.0.0-alpine'
  args:
  - 'bash'
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |-
    gcloud run deploy "generate" \
      --quiet \
      --project "${PROJECT_ID}" \
      --platform "managed" \
      --region "${_REGION}" \
      --image "gcr.io/${PROJECT_ID}/${_REPO}/generate:${_TAG}" \
      --no-traffic
  waitFor:
  - '-'

#
# key-rotation
#
- id: 'deploy-key-rotation'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:307.0.0-alpine'
  args:
  - 'bash'
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |-
    gcloud run deploy "key-rotation" \
      --quiet \
      --project "${PROJECT_ID}" \
      --platform "managed" \
      --region "${_REGION}" \
      --image "gcr.io/${PROJECT_ID}/${_REPO}/key-rotation:${_TAG}" \
      --no-traffic
  waitFor:
  - '-'
