#!/usr/bin/env bash

# Copyright 2020 the Exposure Notifications Server authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eEuo pipefail

ROOT="$(cd "$(dirname "$0")/.." &>/dev/null; pwd -P)"

if [ -n "$(git status --porcelain)" ]; then
  echo "✋ Uncommitted local changes!" >&2
  exit 1
fi

if [ -z "${PROJECT_ID:-}" ]; then
  echo "✋ Missing PROJECT_ID!" >&2
  exit 1
fi

if [ -z "${TAG:-}" ]; then
  TAG="$(git describe --dirty)"
  echo "🎈 Using ${TAG}!" >&2
fi

SUBS="_TAG=${TAG}"
SUBS="${SUBS},_GO_TAGS=${GO_TAGS:-"google"}"
SUBS="${SUBS},_BINAUTHZ_ATTESTOR=${BINAUTHZ_ATTESTOR:-""}"
SUBS="${SUBS},_BINAUTHZ_KEY_VERSION=${BINAUTHZ_KEY_VERSION:-""}"

gcloud builds submit "${ROOT}" \
  --project "${PROJECT_ID}" \
  --config "${ROOT}/builders/build.yaml" \
  --substitutions "${SUBS}"
