#!/usr/bin/env bash

# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eEuo pipefail

ROOT="$(cd "$(dirname "$0")/.." &>/dev/null; pwd -P)"

if [ -z "${PROJECT_ID:-}" ]; then
  echo "✋ Missing PROJECT_ID!" >&2
  exit 1
fi

if [ -z "${TAG:-}" ]; then
  TAG="$(git describe --dirty)"
  echo "🎈 Using ${TAG}!" >&2
fi

SUBS="_TAG=${TAG}"
SUBS="${SUBS},_REGION=${REGION:-"us-central1"}"
# For skipping certain deployment, for example ',SKIP_DEPLOY_CLEANUP_EXPOSURE,SKIP_DEPLOY_CLEANUP_EXPORT'
SUBS="${SUBS},_CONDITION=${DEPLOY_CONDITION:-}"

gcloud builds submit --no-source \
  --project "${PROJECT_ID}" \
  --config "${ROOT}/builders/deploy.yaml" \
  --substitutions "${SUBS}"
