#!/usr/bin/env bash

# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eEuo pipefail

ROOT="$(cd "$(dirname "$0")/.." &>/dev/null; pwd -P)"

# Ensure migrate is installed.
command -v migrate &>/dev/null || {
  echo 1>&2 "Migrate command not found. Have you installed golang-migrate?";
  echo 1>&2 "https://github.com/golang-migrate/migrate/blob/master/cmd/migrate/README.md#installation";
  exit 1;
}

# If DB_URL is unset, fail.
if [ -z "${DB_URL:-}" ]; then
  echo 1>&2 "Missing \$DB_URL - did you run `eval \$(./scripts/dev init)`?"
  exit 1;
fi

# If no args are given, assume "up".
if [ $# -eq 0 ]; then
  set -- "up"
fi

# Run
migrate -database "${DB_URL}" -path "${ROOT}/migrations" "$@"
