#!/usr/bin/env bash

# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eEuo pipefail

ROOT="$(cd "$(dirname "$0")/.." &>/dev/null; pwd -P)"

if [ -z "${PROJECT_ID:-}" ]; then
  echo "✋ Missing PROJECT_ID!" >&2
  exit 1
fi

if [ -z "${DB_CONN:-}" ]; then
  echo "✋ Missing DB_CONN (e.g. my-project:us-central1:my-database)!" >&2
  exit 1
fi

if [ -z "${DB_PASS_SECRET:-}" ]; then
  echo "✋ Missing DB_PASS_SECRET (e.g. projects/my-project/secrets/my-secret/versions/1)!" >&2
  exit 1
fi

if [[ "${DB_PASS_SECRET}" != "projects/"*  ]]; then
  echo "✋ DB_PASS_SECRET does not look like a secret reference!"
  exit 1
fi

if [ -z "${DB_NAME:-}" ]; then
  DB_NAME="main"
  echo "🚧 Using database \"${DB_NAME}\"" >&2
fi

if [ -z "${DB_USER:-}" ]; then
  DB_USER="notification"
  echo "🚧 Using username \"${DB_USER}\"" >&2
fi

if [ -z "${COMMAND:-}" ]; then
  COMMAND="up"
  echo "🚧 Using command \"${COMMAND}\"" >&2
fi

gcloud builds submit "${ROOT}" \
  --config "${ROOT}/builders/migrate.yaml" \
  --substitutions "_COMMAND=${COMMAND},_DB_CONN=${DB_CONN},_DB_NAME=${DB_NAME},_DB_PASS_SECRET=${DB_PASS_SECRET},_DB_USER=${DB_USER}" \
  --project "${PROJECT_ID}"
