#!/usr/bin/env bash

# Copyright 2020 the Exposure Notifications Server authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eEuo pipefail

ROOT="$(cd "$(dirname "$0")/.." &>/dev/null; pwd -P)"

if [ -z "${TAG:-}" ]; then
  TAG="$(git describe --dirty)"
  echo "🎈 Using ${TAG}!" >&2
fi

SUBS="_TAG=${TAG}"
SUBS="${SUBS},_DB_CONN=${DB_CONN}"
SUBS="${SUBS},_DB_HOST=${DB_HOST:-"127.0.0.1"}"
SUBS="${SUBS},_DB_NAME=${DB_NAME:-"main"}"
SUBS="${SUBS},_DB_PASSWORD=${DB_PASSWORD}"
SUBS="${SUBS},_DB_PORT=${DB_PORT:-"5432"}"
SUBS="${SUBS},_DB_SSLMODE=${DB_SSLMODE:-"disable"}"
SUBS="${SUBS},_DB_USER=${DB_USER:-"notification"}"

gcloud builds submit --no-source \
  --project "${PROJECT_ID}" \
  --config "${ROOT}/builders/migrate.yaml" \
  --substitutions "${SUBS}"
