#!/usr/bin/env bash

# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eEuo pipefail

ROOT="$(cd "$(dirname "$0")/.." &>/dev/null; pwd -P)"

if [ -z "${PROJECT_ID:-}" ]; then
  echo "✋ Missing PROJECT_ID!" >&2
  exit 1
fi

SUBS="_PERCENTAGE=${PERCENTAGE:-"100"}"
SUBS="${SUBS},_REGION=${REGION:-"us-central1"}"
SUBS="${SUBS},_REVISION=${REVISION:-"LATEST"}"
SUBS="${SUBS},_SKIP-DEPLOY-CLEANUP-EXPOSURE=${SKIP-DEPLOY-CLEANUP-EXPOSURE:-false}"
SUBS="${SUBS},_SKIP-DEPLOY-CLEANUP-EXPORT=${SKIP-DEPLOY-CLEANUP-EXPORT:-false}"
SUBS="${SUBS},_SKIP-DEPLOY-DEBUGGER=${SKIP-DEPLOY-DEBUGGER:-false}"
SUBS="${SUBS},_SKIP-DEPLOY-EXPORT=${SKIP-DEPLOY-EXPORT:-false}"
SUBS="${SUBS},_SKIP-DEPLOY-EXPOSURE=${SKIP-DEPLOY-EXPOSURE:-false}"
SUBS="${SUBS},_SKIP-DEPLOY-FEDERATIONIN=${SKIP-DEPLOY-FEDERATIONIN:-false}"
SUBS="${SUBS},_SKIP-DEPLOY-FEDERATIONOUT=${SKIP-DEPLOY-FEDERATIONOUT:-false}"
SUBS="${SUBS},_SKIP-DEPLOY-GENERATE=${SKIP-DEPLOY-GENERATE:-false}"
SUBS="${SUBS},_SKIP-DEPLOY-KEY-ROTATION=${SKIP-DEPLOY-KEY-ROTATION:-false}"

gcloud builds submit --no-source \
  --project "${PROJECT_ID}" \
  --config "${ROOT}/builders/promote.yaml" \
  --substitutions "${SUBS}"
