name: Code Review

on:
  pull_request:
    branches: [ 'main' ]

jobs:

  donotsubmit:
    name: Reminder
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Reminder
        shell: bash
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
        run: |
          set -e
          cd "${GITHUB_WORKSPACE}" || exit 1
          TEMP_PATH="$(mktemp -d)"
          PATH="${TEMP_PATH}:$PATH"
          echo '::group::🐶 Installing reviewdog ... https://github.com/reviewdog/reviewdog'
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b "${TEMP_PATH}" 2>&1
          echo '::endgroup::'
          echo '::group:: Running Reminder with reviewdog 🐶 ...'
          # Don't fail because of grep
          set +o pipefail
          find . -type f -not -path './.git/*' -not -path './.github/workflows/*' |
          xargs grep -n ".Errorw" |
          reviewdog -efm="%f:%l:%m" \
                -name="Make sure this is not a user error" \
                -reporter="github-pr-check" \
                -filter-mode="added" \
                -fail-on-error="false" \
                -level="info"
          echo '::endgroup::'
